[plugins]
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning:7.0.7"
taskTree = "com.dorongold.task-tree:4.0.1"
node = "com.github.node-gradle.node:7.1.0"

[versions]
node = "22.14.0"
npm = "10.9.2"

